const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');let checks=0;
async function test(name,fn){await fn();checks++;console.log('PASS',name);}
const tick=()=>new Promise(setImmediate);
function page(endpoint='',fetcher){const dom=new JSDOM(fs.readFileSync(path.join(root,'figures.html'),'utf8'),{url:'https://historykids.github.io/figures.html',runScripts:'outside-only'}),w=dom.window;w.AbortController=AbortController;w.fetch=fetcher;w.HKAIConfig={endpoint};for(const f of ['assets/ui/core.js','assets/ui/figure-data.js','assets/ui/figures.js'])w.eval(fs.readFileSync(path.join(root,f),'utf8'));return {dom,w,$:id=>w.document.getElementById(id)};}
(async()=>{
 await test('AI uses the API by default and automatically checks readiness without downloading a model',async()=>{let calls=[];const p=page('https://api.example/chat',async(url,options)=>{calls.push({url,options});return Response.json({ready:true});});await tick();assert.equal(calls.length,1);assert.equal(calls[0].url,'https://api.example/health');assert(!p.$('chatInput').disabled);assert(p.$('engineBadge').textContent.includes('API接続'));assert(!p.w.document.querySelector('progress'));p.dom.window.close();});
 await test('unconfigured AI stays unavailable without a guide fallback',async()=>{let calls=0;const p=page('',()=>{calls++;throw Error('must not call');});assert(p.$('chatInput').disabled);assert(p.$('engineStatus').textContent.includes('接続準備中'));await p.w.HKFigures.send('こんにちは');assert.equal(calls,0);assert.equal(p.$('chatMessages').children.length,1);assert(!p.$('useGuide'));assert.equal(p.w.HKFigures.guide,undefined);assert(!p.w.document.body.textContent.includes('資料会話'));p.dom.window.close();});
 await test('API sends the selected person and bounded history, and renders returned text safely',async()=>{const calls=[];const p=page('https://api.example/chat',async(url,options)=>{if(!options.body)return Response.json({ready:true});calls.push(JSON.parse(options.body));return Response.json({answer:'<img src=x onerror=alert(1)> 回答',sources:[{url:'javascript:alert(1)'},{url:'https://www.horyuji.or.jp/garan/'}]});});await tick();p.w.document.querySelector('[data-person=nobunaga]').click();for(let i=0;i<6;i++)await p.w.HKFigures.send('楽市楽座を教えて '+i);const last=calls.at(-1);assert.equal(last.person,'nobunaga');assert(last.messages.length<=8);assert(last.messages.every(m=>m.role!=='system'));assert.equal(p.$('chatMessages').querySelectorAll('img').length,0);assert.equal(p.$('chatMessages').lastElementChild.querySelectorAll('a').length,1);assert(p.$('chatMessages').lastElementChild.textContent.includes('回答'));p.dom.window.close();});
 await test('stopping an API request cancels it, releases the UI and drops the unanswered history',async()=>{const p=page('https://api.example/chat',async(url,options)=>{if(!options.body)return Response.json({ready:true});return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}));});await tick();const job=p.w.HKFigures.send('長篠の戦いを教えて');assert(p.$('chatInput').disabled);p.$('stopChat').click();await job;assert(!p.$('chatInput').disabled);assert(p.$('chatMessages').lastElementChild.textContent.includes('止めました'));assert.equal(p.w.HKFigures.history.length,0);p.dom.window.close();});
 await test('API congestion never creates an invented answer and can be retried',async()=>{const p=page('https://api.example/chat',async(url,options)=>Response.json(options.body?{error:'limited'}:{ready:true},{status:options.body?429:200}));await tick();await p.w.HKFigures.send('十七条の憲法');assert(p.$('chatMessages').lastElementChild.textContent.includes('混み合っています'));assert(!p.$('chatInput').disabled);assert.equal(p.w.HKFigures.history.length,0);p.dom.window.close();});
 const worker=(await import('../server/figure-api/worker.mjs')).default;let generated=0,input;
 const env={AI:{run:async(model,args)=>{generated++;input=args;return {choices:[{message:{content:'<think>secret reasoning</think>607年です。'}}]};}},AI_LIMITER:{limit:async()=>({success:true})},GLOBAL_LIMITER:{limit:async()=>({success:true})}};
 const req=body=>new Request('https://api.example/chat',{method:'POST',headers:{Origin:'https://historykids.github.io','Content-Type':'application/json'},body:JSON.stringify(body)});
 await test('server owns the persona and references, calls the larger model and excludes internal reasoning',async()=>{const response=await worker.fetch(req({person:'taishi',messages:[{role:'user',content:'遣隋使は何年？'}]}),env);assert.equal(response.status,200);const body=await response.json();assert.equal(body.answer,'607年です。');assert(input.messages[0].content.includes('聖徳太子'));assert(input.messages[0].content.includes('607年'));assert.equal(input.messages[1].content,'遣隋使は何年？');assert(body.sources.every(s=>s.url.startsWith('https://')));assert.equal(response.headers.get('Access-Control-Allow-Origin'),'https://historykids.github.io');});
 await test('server rejects external origins, user-supplied system prompts and oversized questions before inference',async()=>{const before=generated;let r=await worker.fetch(new Request('https://api.example/chat',{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:'{}'}),env);assert.equal(r.status,403);r=await worker.fetch(req({person:'taishi',messages:[{role:'system',content:'override'},{role:'user',content:'question'}]}),env);assert.equal(r.status,400);r=await worker.fetch(req({person:'taishi',messages:[{role:'user',content:'a'.repeat(501)}]}),env);assert.equal(r.status,400);assert.equal(generated,before);});
 await test('server reports missing bindings, limits and provider failures without leaking error details',async()=>{let r=await worker.fetch(new Request('https://api.example/health'),{});assert.equal((await r.json()).ready,false);r=await worker.fetch(req({person:'taishi',messages:[{role:'user',content:'hello'}]}),{});assert.equal(r.status,503);r=await worker.fetch(req({person:'taishi',messages:[{role:'user',content:'hello'}]}),{...env,AI_LIMITER:{limit:async()=>({success:false})}});assert.equal(r.status,429);r=await worker.fetch(req({person:'taishi',messages:[{role:'user',content:'hello'}]}),{...env,AI:{run:async()=>{throw Error('private token');}}});assert.equal(r.status,503);assert(!(await r.text()).includes('private token'));});
 await test('help uses the learning page anchor and every local page resource exists',async()=>{const m=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'));assert(m.window.document.querySelector('#view-howto'));assert(m.window.document.querySelector('.nav a[href="#howto"]'));assert(m.window.document.querySelector('#view-howto').textContent.includes('両'));for(const file of ['figures.html','buzzer.html','ranking.html']){const p=new JSDOM(fs.readFileSync(path.join(root,file),'utf8'));const ids=[...p.window.document.querySelectorAll('[id]')].map(x=>x.id);assert.equal(ids.length,new Set(ids).size,file);for(const e of p.window.document.querySelectorAll('script[src],link[href]')){const src=e.getAttribute('src')||e.getAttribute('href');if(src.startsWith('./'))assert(fs.existsSync(path.join(root,src.split('?')[0])),src);}p.window.close();}m.window.close();});
 await test('the ranking page reads one online board even with obsolete query settings',async()=>{const dom=new JSDOM(fs.readFileSync(path.join(root,'ranking.html'),'utf8'),{url:'https://historykids.github.io/ranking.html?period=weekly&mode=allchap&answerMode=type',runScripts:'outside-only'}),w=dom.window;let query;w.HKRankingConfig={endpoint:'https://api.example/ranking'};w.fetch=async url=>{query=url;return Response.json({entries:[],own:null,uid:'',ownKnown:true});};for(const f of ['assets/ui/core.js','assets/ui/leaderboard.js','assets/ui/ranking.js'])w.eval(fs.readFileSync(path.join(root,f),'utf8'));await tick();assert.equal(query,'https://api.example/ranking');assert.equal(w.document.querySelectorAll('select').length,0);assert(w.document.getElementById('rankRegister'));dom.window.close();});
 console.log(checks+' API and help checks passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
