const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),R=require(path.join(root,'assets/ui/casino-rules.js'));
let checks=0;
async function test(name,fn){await fn();checks++;console.log('PASS',name);}
function page({balance=100,storage=null,ui=false,locks=null}={}){
 const map=storage||new Map([['money_v1',String(balance)]]),dom=new JSDOM(ui?read('casino.html'):'<body></body>',{url:'https://historykids.github.io/casino.html',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
 Object.defineProperty(w,'localStorage',{value:{getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k)}});
 w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollIntoView=function(){};
 if(locks)Object.defineProperty(w.navigator,'locks',{value:locks});
 let next=0,values=[],count=0;w.crypto.getRandomValues=a=>{a[0]=values.length?values.shift():next;return a;};w.crypto.randomUUID=()=>`test-round-${++count}`;
 let now=0,id=0;const timers=new Map();w.setTimeout=(fn,delay=0)=>{const i=++id;timers.set(i,{fn,due:now+delay});return i;};w.clearTimeout=i=>timers.delete(i);
 w.eval(read('assets/ui/wallet.js'));if(ui){w.eval(read('assets/ui/casino-rules.js'));w.eval(read('assets/ui/casino.js'));}
 const advance=ms=>{const end=now+ms;let safety=0;while(true){const t=[...timers].sort((a,b)=>a[1].due-b[1].due)[0];if(!t||t[1].due>end)break;assert(safety++<1000);now=t[1].due;timers.delete(t[0]);t[1].fn();}now=end;};
 return {dom,w,W:w.HKWallet,map,$:id=>w.document.getElementById(id),advance,setRandom:n=>{next=n;},setSequence:v=>{values=v.slice();}};
}
function walletCall(W,method,...args){return new Promise((resolve,reject)=>W[method](...args,resolve,reject));}
async function main(){
 await test('janken obeys all nine outcomes and returns the stake on a tie',()=>{const matrix=[[1,2,0],[0,1,2],[2,0,1]];for(let a=0;a<3;a++)for(let b=0;b<3;b++)assert.equal(R.janken(a,b),matrix[a][b]);assert.throws(()=>R.janken(3,0));});
 await test('roulette uses the 37-pocket European sequence and zero loses every outside bet',()=>{assert.equal(R.wheel.length,37);assert.equal(new Set(R.wheel).size,37);assert.equal(R.wheel[0],0);for(const id of ['red','black','odd','even','low','high','d1','d2','d3','c1','c2','c3'])assert.equal(R.roulette([{id,stake:10}],0),0);assert.equal(R.roulette([{id:'n0',stake:10}],0),360);});
 await test('every supported roulette bet has correct coverage, payout and expected return',()=>{for(const id of ['red','black','odd','even','low','high','d1','d2','d3','c1','c2','c3',...Array.from({length:37},(_,i)=>'n'+i)]){const b=R.bet(id);assert.equal(b.numbers.length*b.multiplier,36,id);assert.equal(Array.from({length:37},(_,i)=>R.roulette([{id,stake:1}],i)).reduce((a,b)=>a+b,0),36,id);}assert.equal(R.roulette([{id:'n1',stake:5},{id:'red',stake:10},{id:'d1',stake:5}],1),215);assert.throws(()=>R.bet('n37'));assert.throws(()=>R.roulette([{id:'red',stake:-1}],1));});
 await test('all 8000 slot stops obey the published paytable and yield exactly 96.95 percent RTP',()=>{assert.equal(R.strip.length,20);let paid=0;for(const a of R.strip)for(const b of R.strip)for(const c of R.strip)paid+=R.slots([a,b,c]).multiplier;assert.equal(paid,7756);assert.equal(R.slots(['seven','seven','seven']).multiplier,250);assert.equal(R.slots(['cherry','bell','cherry']).multiplier,1);assert.equal(R.slots(['lemon','bell','seven']).multiplier,0);assert.throws(()=>R.slots(['fake','fake','fake']));});
 await test('random selection rejects the biased tail of the uint32 range',()=>{const p=page({ui:true});p.setSequence([4294967295,0]);assert.equal(p.w.HKCasinoRules.randomIndex(37),0);p.w.close();});
 await test('the wallet migrates existing town coins, deducts first and pays a win exactly once',async()=>{const p=page({balance:100});const r=await walletCall(p.W,'begin','janken',10,()=>({payout:20,data:{player:0,opponent:1,multiplier:2}}));assert.equal(p.W.snapshot().balance,90);assert(p.W.snapshot().pending);await walletCall(p.W,'finish',r.id);assert.equal(p.W.snapshot().balance,110);assert.equal(p.map.get('money_v1'),'110');const retry=await walletCall(p.W,'finish',r.id);assert(retry.already);assert.equal(p.W.snapshot().balance,110);assert.equal(p.W.snapshot().history.length,1);p.w.close();});
 await test('integer, currency balance, round cap and pending-round checks reject invalid wagers without a debit',async()=>{const p=page({balance:30});for(const stake of [0,-1,1.5,NaN,Infinity,1001,31])await assert.rejects(walletCall(p.W,'begin','slots',stake,()=>({payout:0,data:{}})));assert.equal(p.W.snapshot().balance,30);const r=await walletCall(p.W,'begin','janken',10,()=>({payout:0,data:{}}));await assert.rejects(walletCall(p.W,'begin','janken',10,()=>({payout:0,data:{}})),/pending-round/);await walletCall(p.W,'finish',r.id);assert.equal(p.W.snapshot().balance,20);p.w.close();});
 await test('storage failure leaves the old balance intact and never starts a wager',async()=>{const p=page({balance:50});p.w.localStorage.setItem=()=>{throw Error('denied');};await assert.rejects(walletCall(p.W,'begin','janken',10,()=>({payout:20,data:{}})),/denied/);assert.equal(p.W.snapshot().balance,50);assert.equal(p.W.snapshot().pending,null);p.w.close();});
 await test('concurrent casino tabs share a lock and cannot spend the same coins twice',async()=>{let queue=Promise.resolve();const locks={request:(_,fn)=>{const result=queue.then(fn);queue=result.catch(()=>{});return result;}};const shared=new Map([['money_v1','15']]),a=page({storage:shared,locks}),b=page({storage:shared,locks});const rounds=await Promise.allSettled([walletCall(a.W,'begin','janken',10,()=>({payout:20,data:{}})),walletCall(b.W,'begin','janken',10,()=>({payout:20,data:{}}))]);assert.equal(rounds.filter(r=>r.status==='fulfilled').length,1);assert.equal(a.W.snapshot().balance,5);const round=rounds.find(r=>r.status==='fulfilled').value;await Promise.all([walletCall(a.W,'finish',round.id),walletCall(b.W,'finish',round.id)]);assert.equal(a.W.snapshot().balance,25);a.w.close();b.w.close();});
 await test('town spending and quiz rewards cannot overwrite a casino balance, and reset voids old pending rounds',async()=>{const shared=new Map([['money_v1','100']]),a=page({storage:shared}),b=page({storage:shared});const r=await walletCall(a.W,'begin','janken',10,()=>({payout:20,data:{}}));await walletCall(b.W,'adjust',-30);await walletCall(b.W,'adjust',20);await walletCall(a.W,'finish',r.id);assert.equal(a.W.snapshot().balance,100);const next=await walletCall(a.W,'begin','janken',10,()=>({payout:20,data:{}}));await walletCall(b.W,'replace',50);await assert.rejects(walletCall(a.W,'finish',next.id),/round-gone/);assert.equal(a.W.snapshot().balance,50);a.w.close();b.w.close();});
 await test('a cancelled town purchase waiting on the wallet lock cannot consume coins',async()=>{let release;const locks={request:(_,fn)=>new Promise((resolve,reject)=>{release=()=>{try{resolve(fn());}catch(e){reject(e);}};})},p=page({locks});let valid=true;const result=walletCall(p.W,'buy',30,()=>valid);valid=false;release();await assert.rejects(result,/purchase-cancelled/);assert.equal(p.W.snapshot().balance,100);p.w.close();});
 await test('mobile controls use the same stake and cannot double-charge a desktop button',()=>{const p=page({ui:true});p.$('mobileStake').value='5';p.$('mobileStake').dispatchEvent(new p.w.Event('input'));assert.equal(p.$('stake').value,'5');assert.equal(p.$('mobileBetTotal').textContent,'5両');p.setRandom(0);p.$('mobilePlayRound').click();p.$('playRound').click();assert.equal(p.W.snapshot().balance,95);assert(p.$('mobilePlayRound').disabled);p.advance(2000);assert.equal(p.W.snapshot().balance,100);assert.equal(p.W.snapshot().history.length,1);p.w.close();});
 await test('janken UI locks a running round, reveals the right hands and credits only its real payout',()=>{const p=page({ui:true});p.setRandom(1);p.$('playRound').click();p.$('playRound').click();assert.equal(p.W.snapshot().balance,90);assert(p.$('playRound').disabled);assert(p.w.document.querySelector('[data-game="slots"]').disabled);p.advance(2000);assert.equal(p.W.snapshot().balance,110);assert(p.$('resultHeadline').textContent.includes('あなたの勝ち'));assert.equal(p.$('resultNet').textContent,'＋10両');assert.equal(p.$('opponentHand').textContent,'✌️');p.advance(5000);assert.equal(p.W.snapshot().balance,110);p.w.close();});
 await test('roulette chips can be removed, charge only on spin and settle multiple covered positions',()=>{const p=page({ui:true,balance:500});p.w.document.querySelector('[data-game="roulette"]').click();p.w.document.querySelector('[data-position="n0"]').click();p.w.document.querySelector('[data-position="red"]').click();assert.equal(p.$('rouletteTotal').textContent,'20両');assert.equal(p.W.snapshot().balance,500);p.$('undoBet').click();assert.equal(p.$('rouletteTotal').textContent,'10両');p.setRandom(0);p.$('playRound').click();assert.equal(p.W.snapshot().balance,490);p.advance(5200);assert.equal(p.W.snapshot().balance,850);assert.equal(p.$('wheelNumber').textContent,'0');assert.equal(p.$('rouletteTotal').textContent,'0両');assert.equal(p.$('resultPayout').textContent,'360両');p.w.close();});
 await test('slots stop one reel at a time and a real 777 credits the displayed 250x amount',()=>{const p=page({ui:true});p.w.document.querySelector('[data-game="slots"]').click();p.setRandom(19);p.$('playRound').click();assert.equal(p.W.snapshot().balance,90);p.advance(1800);assert(p.$('reel0').parentElement.classList.contains('stopped'));assert(!p.$('reel2').parentElement.classList.contains('stopped'));p.advance(1300);assert.equal(p.W.snapshot().balance,2590);assert.equal(p.$('resultPayout').textContent,'2,500両');assert(p.$('tableArea').classList.contains('big-win'));const track=p.$('reel2');assert(track.innerHTML.includes('symbol-seven'));p.w.close();});
 await test('reopening an unfinished round restores its exact result without a second stake or payout',()=>{const map=new Map([['money_v1','100']]),first=page({ui:true,storage:map});first.setRandom(1);first.$('playRound').click();assert.equal(first.W.snapshot().balance,90);const second=page({ui:true,storage:map});assert.equal(second.W.snapshot().balance,110);assert.equal(second.$('resultKicker').textContent,'RESULT RESTORED');first.advance(2000);assert.equal(first.W.snapshot().balance,110);assert.equal(first.W.snapshot().history.length,1);first.w.close();second.w.close();});
 await test('all three cards use the same casino page, VEX10 is gone, and small screens get dedicated layout rules',()=>{const index=read('index.html');for(const game of ['janken','roulette','slots'])assert(index.includes('./casino.html?game='+game));for(const file of ['index.html','arcade.html','edogames.html','assets/ui/arcade.js','assets/ui/arcade.css'])assert(!/vex|gamedistribution/i.test(read(file)),file);assert(read('assets/ui/casino.css').includes('@media(max-width:420px)'));assert(read('casino.html').includes('現金・別のチップは使いません'));});
 console.log(`\n${checks} casino and shared-wallet checks passed.`);
}
main().catch(error=>{console.error(error);process.exitCode=1;});
