const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), { JSDOM } = require('jsdom');
const root = path.resolve(__dirname, '..'), C = require(path.join(root, 'assets/ui/core.js')); let checks = 0;
function test(name, run) { run(); checks++; console.log('PASS', name); }
function page(config = {}) {
  const dom = new JSDOM(fs.readFileSync(path.join(root,'buzzer.html'),'utf8'), { url:'https://historykids.github.io/buzzer.html',runScripts:'outside-only',pretendToBeVisual:true });
  const w=dom.window;let now=0;w.HTMLElement.prototype.scrollIntoView=function(){};Object.defineProperty(w.performance,'now',{value:()=>now});w.setInterval=()=>1;w.clearInterval=()=>{};
  for(const file of ['data/dataset.js','data/ancient.js','assets/ui/core.js','assets/ui/leaderboard.js','assets/ui/challenge.js'])w.eval(fs.readFileSync(path.join(root,file),'utf8'));
  const $=id=>w.document.getElementById(id),click=s=>{const e=w.document.querySelector(s);assert(e,s);e.click();};
  let navigation="";$("submittedRanking").addEventListener("click",event=>{event.preventDefault();navigation=$("submittedRanking").getAttribute("href");});
  if(config.game)click(`[data-game="${config.game}"]`);
  const time=t=>{now=t;w.HKChallenge.tick();};
  const start=()=>{click('#startBtn');time(3000);};
  const answer=(correct=true)=>{click('#buzzBtn');const q=w.HKChallenge.run.qs[w.HKChallenge.qi];if(w.HKChallenge.run.answerMode==='choice'){const buttons=[...w.document.querySelectorAll('[data-choice]')];buttons.find(b=>C.answerOK(b.dataset.choice,q.answers)===correct).click();}else{$('answer').value=correct?q.answers.join('・'):'まちがい';$('challengeForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}};
  return {dom,w,$,click,time,start,answer,get now(){return now;},get navigation(){return navigation;}};
}
test('countdown protects answers and elapsed time begins at zero',()=>{const p=page();p.click('#startBtn');p.click('#buzzBtn');assert.equal(p.w.HKChallenge.run.phase,'countdown');p.time(2999);assert.equal(p.$('countdown').textContent,'1');p.time(3000);assert.equal(p.w.HKChallenge.run.phase,'reading');assert.equal(p.$('timerText').textContent,'0.00秒');p.dom.window.close();});
test('questions reveal gradually and freeze when the buzzer is pressed',()=>{const p=page();p.start();p.time(3240);const short=p.$('qTitle').textContent;assert(short.length>0&&short.length<p.w.HKChallenge.run.qs[0].prompt.length);p.click('#buzzBtn');p.time(3500);assert.equal(p.$('qTitle').textContent,short);const options=[...p.w.document.querySelectorAll('[data-choice]')].map(b=>b.dataset.choice);assert.equal(new Set(options.map(s=>[...s].length)).size,1);p.dom.window.close();});
test('wrong answers charge one penalty, break the combo, and save the question for review',()=>{const p=page();p.start();p.answer();p.click('#nextBtn');p.answer(false);assert.equal(p.w.HKChallenge.run.penalty,5000);assert.equal(p.w.HKChallenge.run.combo,0);p.answer(false);assert.equal(p.w.HKChallenge.run.penalty,5000);const q=p.w.HKChallenge.run.log[1].q;assert(JSON.parse(p.w.localStorage.getItem('hk_wrong_v2'))[q.id]);p.dom.window.close();});
test('answer timeout and automatic advance cannot resolve the same round twice',()=>{const p=page();p.start();p.click('#buzzBtn');p.time(18001);assert.equal(p.w.HKChallenge.run.misses,1);p.time(18002);assert.equal(p.w.HKChallenge.run.misses,1);p.time(21000);assert.equal(p.w.HKChallenge.qi,1);assert.equal(p.w.HKChallenge.run.phase,'reading');p.click('#nextBtn');assert.equal(p.w.HKChallenge.qi,1);p.dom.window.close();});
test('60-second rush ends at its limit and does not accept late answers',()=>{const p=page({game:'rush'});p.start();p.answer();p.click('#nextBtn');p.click('#buzzBtn');p.time(63000);assert.equal(p.w.HKChallenge.run.phase,'finished');assert.equal(p.w.HKChallenge.run.correct,1);p.answer();assert.equal(p.w.HKChallenge.run.correct,1);assert(!p.$('submitBox').hidden);assert(p.$('submit').disabled);p.dom.window.close();});
test('three mistakes finish survival and surrender clears the active run',()=>{const p=page({game:'survival'});p.start();for(let i=0;i<3;i++){p.answer(false);if(i<2)p.click('#nextBtn');}assert.equal(p.w.HKChallenge.run.phase,'finished');assert.equal(p.w.HKChallenge.run.lives,0);assert.equal(p.w.HKChallenge.run.log.length,3);assert(!p.$('submitBox').hidden);assert(p.$('submit').disabled);p.click('#settingsBtn');assert.equal(p.w.HKChallenge.run,null);assert(!p.$('startBox').hidden);assert(!p.w.document.querySelector('[data-game]').disabled);p.dom.window.close();});
test('buzzer rules are all-time, all eras and four choices, with one question per era',()=>{const p=page();p.start();const run=p.w.HKChallenge.run;assert.equal(run.period,'alltime');assert.equal(run.key,'ALL');assert.equal(run.era,'ALL');assert.equal(run.answerMode,'choice');assert.equal(new Set(run.qs.map(q=>q.era)).size,10);assert.equal(p.w.document.querySelectorAll('#startBox select').length,0);p.dom.window.close();});
test('keyboard buzzer and choice work while repeated keys cannot double-answer',()=>{const p=page();p.start();p.w.document.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:' ',code:'Space',bubbles:true,cancelable:true}));assert.equal(p.w.HKChallenge.run.phase,'answer');const q=p.w.HKChallenge.run.qs[0],i=[...p.w.document.querySelectorAll('[data-choice]')].findIndex(b=>C.answerOK(b.dataset.choice,q.answers));p.w.document.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:String(i+1),bubbles:true,cancelable:true}));assert.equal(p.w.HKChallenge.run.correct,1);p.w.document.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:String(i+1),repeat:true,bubbles:true}));assert.equal(p.w.HKChallenge.run.correct,1);p.dom.window.close();});
test('new distractors keep exact lengths and use geography or religion instead of unrelated words',()=>{const p=page();p.start();const q={id:'a',answers:['えど']};const city=C.choiceAnswers(q,[]);assert.deepEqual(new Set(city),new Set(['えど','なら','みと','さが']));const religion=new Set(['じょうど','りんざい','にちれん','そうとう','じしゅう']);for(const correct of religion)for(const choice of C.choiceAnswers({id:correct,answers:[correct]},[]))assert(religion.has(choice));p.dom.window.close();});
(async()=>{
 const p=page({answers:'type'});p.start();for(let i=0;i<10;i++){p.time(3000+i*300);p.answer();if(i<9)p.click('#nextBtn');}
 test('perfect games save combo, review rows and use the unified all-time ranking group',()=>{assert.equal(p.w.HKChallenge.run.maxCombo,10);assert.equal(p.$('resultReview').querySelectorAll('details').length,10);assert.equal(p.w.HKChallenge.run.group,'v4_allera_ALL_choice');assert(!p.$('submitBox').hidden);assert(JSON.parse(p.w.localStorage.getItem(p.w.HKChallenge.run.scoreKey)).correct===10);assert.equal(p.$('player').labels[0].textContent,'ニックネームを入力');});

 let sends=0;p.w.HKLeaderboard.registerableBest=()=>({correct:10,ms:2700,proof:'verified-proof'});p.$('submit').disabled=false;
 // Re-enter a completed run with a verified local receipt to exercise registration UI.
 p.time(0);p.click('#againBtn');p.time(3000);for(let i=0;i<10;i++){p.time(3000+i*300);p.answer();if(i<9)p.click('#nextBtn');}
 p.w.HKRankingConfig={endpoint:'https://api.example/ranking'};p.w.localStorage.setItem(p.w.HKLeaderboard.verifiedKey,JSON.stringify({correct:10,ms:2700,proof:'verified-proof'}));
 p.w.fetch=async(url,options)=>{sends++;return Response.json({updated:true,entry:{id:'tester',name:JSON.parse(options.body).name,ms:2700,timestamp:1}});};
 p.$('player').value='　　';p.$('rankingForm').dispatchEvent(new p.w.Event('submit',{bubbles:true,cancelable:true}));await new Promise(setImmediate);
 test('a blank nickname cannot publish a score and result nickname entry remains visible',()=>{assert.equal(sends,0);assert(p.$('player').validationMessage.includes('入力'));assert(!p.$('submitBox').hidden);assert(!p.$('submit').disabled);});p.$('player').value='';p.$('player').dispatchEvent(new p.w.Event('input'));
 let written;p.w.fetch=async(url,options)=>{written=JSON.parse(options.body);return Response.json({updated:true,entry:{id:'tester',name:written.name,ms:2700,timestamp:1}});};p.$('player').value='<script>test</script>';p.click('#submit');await new Promise(setImmediate);await new Promise(setImmediate);
 test('online submission sends the nickname and verified proof without a client-supplied time',()=>{assert(written);assert.equal(written.name,'<script>test</script>');assert.equal(written.proof,'verified-proof');assert.equal(written.ms,undefined);assert.equal(p.w.localStorage.getItem('hk_buzzer_nickname'),written.name);assert(p.$('submit').disabled);assert(p.$('submitStatus').textContent.includes('ランキング登録できた'));assert(!p.$('submittedRanking').hidden);assert.equal(p.$('submitStatus').querySelectorAll('script').length,0);assert.equal(p.navigation,'./ranking.html?registered=1#personalCard');assert.equal(p.w.HKLeaderboard.readPublished().entry.name,written.name);});p.dom.window.close();
 for(const oldMs of [2400,3000]){
  const q=page();q.w.HKLeaderboard.registerableBest=()=>({correct:10,ms:2700,proof:'verified-proof'});q.w.localStorage.setItem(q.w.HKLeaderboard.verifiedKey,JSON.stringify({correct:10,ms:2700,proof:'verified-proof'}));q.start();for(let i=0;i<10;i++){q.time(3000+i*300);q.answer();if(i<9)q.click('#nextBtn');}
  let sends=0;q.w.HKRankingConfig={endpoint:'https://api.example/ranking'};q.w.fetch=async()=>{sends++;return Response.json({updated:oldMs>2700,entry:{id:'tester',name:'歴史名人',ms:Math.min(oldMs,2700),timestamp:1}});};
  q.$('player').value='歴史名人';q.click('#submit');await new Promise(setImmediate);await new Promise(setImmediate);
  test(oldMs<2700?'all-time rankings report the faster existing record':'all-time rankings show an improved verified best',()=>{assert.equal(sends,1);assert(q.$('submitStatus').textContent.includes(oldMs<2700?'速いよ':'登録できた'));});q.dom.window.close();
 }
 const rename=page();rename.w.localStorage.setItem(rename.w.HKLeaderboard.verifiedKey,JSON.stringify({correct:10,ms:2700,proof:'verified-proof'}));rename.start();for(let i=0;i<10;i++){rename.time(3000+i*300);rename.answer();if(i<9)rename.click('#nextBtn');}
 rename.w.HKRankingConfig={endpoint:'https://api.example/ranking'};rename.w.fetch=async()=>{throw Error('offline');};rename.$('player').value='選んだ名前';rename.click('#submit');await new Promise(setImmediate);await new Promise(setImmediate);
 test('failed registration stays on the result screen and allows a retry without claiming publication',()=>{assert.equal(rename.navigation,'');assert(!rename.$('submit').disabled);assert(rename.$('submitStatus').textContent.includes('通信'));assert.equal(rename.w.HKLeaderboard.readPublished(),null);});
 rename.w.fetch=async()=>Response.json({updated:true,renamed:true,entry:{id:'tester',name:'選んだ名前',ms:2400,timestamp:1}});rename.click('#submit');await new Promise(setImmediate);await new Promise(setImmediate);
 test('registering a selected nickname keeps the faster best and opens the personal ranking',()=>{assert(rename.$('submitStatus').textContent.includes('選んだ名前に名前を変更'));assert(rename.$('submitStatus').textContent.includes('2.40秒'));assert.equal(rename.navigation,'./ranking.html?registered=1#personalCard');assert.equal(rename.w.HKLeaderboard.readPublished().entry.name,'選んだ名前');});rename.w.close();
 const online=page();online.w.HKRankingConfig={endpoint:'https://api.example/ranking'};let session;
 online.w.fetch=async(url,options)=>{if(url.endsWith('/start')){session={ticket:'test-ticket',ids:online.w.HKCore.eraOrder.map(era=>{const name=Object.keys(Object.values(online.w.dataSets[era].chapters)[0])[0];return era+'|'+name;})};return Response.json(session);}if(url.endsWith('/finish')){const sent=JSON.parse(options.body);assert.equal(sent.ticket,session.ticket);assert.equal(sent.answers.length,10);return Response.json({ms:5000,elapsedMs:5000,proof:'server-proof',timestamp:1});}throw Error('unexpected');};
 online.click('#startBtn');assert.equal(online.w.HKChallenge.run.phase,'connecting');await new Promise(setImmediate);online.time(3000);for(let i=0;i<10;i++){online.time(3000+i*400);online.answer();if(i<9)online.click('#nextBtn');}await new Promise(setImmediate);await new Promise(setImmediate);
 test('online games use server-chosen questions and only enable publishing after verification',()=>{assert.equal(online.w.HKChallenge.run.ticket,'test-ticket');assert.equal(online.$('resultTime').textContent,'5.00秒');assert(!online.$('submit').disabled);assert.equal(online.w.HKLeaderboard.registerableBest().proof,'server-proof');assert.equal(online.w.HKLeaderboard.localBest().ms,5000);});online.dom.window.close();

 const retry=page();retry.w.HKRankingConfig={endpoint:'https://api.example/ranking'};let retrySession,finishCalls=0,registerCalls=0;
 retry.w.fetch=async(url,options)=>{if(url.endsWith('/start')){retrySession={ticket:'retry-ticket',ids:retry.w.HKCore.eraOrder.map(era=>era+'|'+Object.keys(Object.values(retry.w.dataSets[era].chapters)[0])[0])};return Response.json(retrySession);}if(url.endsWith('/finish')){finishCalls++;if(finishCalls===1)throw Error('temporary');return Response.json({ms:6000,elapsedMs:6000,proof:'retry-proof'});}if(url.endsWith('/register')){registerCalls++;assert.equal(JSON.parse(options.body).proof,'retry-proof');return Response.json({updated:true,entry:{id:'retry',name:'再確認',ms:6000,timestamp:1}});}throw Error('unexpected');};
 retry.click('#startBtn');await new Promise(setImmediate);retry.time(3000);for(let i=0;i<10;i++){retry.time(3000+i*400);retry.answer();if(i<9)retry.click('#nextBtn');}await new Promise(setImmediate);await new Promise(setImmediate);
 test('failed verification preserves the perfect local result and offers a retry',()=>{assert.equal(retry.w.HKLeaderboard.localBest().correct,10);assert.equal(retry.w.HKLeaderboard.registerableBest(),null);assert(!retry.$('submit').disabled);assert(retry.$('submitStatus').textContent.includes('通信'));assert.equal(retry.navigation,'');});
 retry.$('player').value='再確認';retry.click('#submit');await new Promise(setImmediate);await new Promise(setImmediate);await new Promise(setImmediate);
 test('one retry click verifies the result and publishes with the entered nickname',()=>{assert.equal(finishCalls,2);assert.equal(registerCalls,1);assert(retry.$('submitStatus').textContent.includes('登録できた'));assert(retry.$('submit').disabled);});retry.dom.window.close();
 const partial=page();partial.w.HKRankingConfig={endpoint:'https://api.example/ranking'};let partialSession,partialWrites=0;
 partial.w.fetch=async(url,options)=>{if(url.endsWith('/start')){partialSession={ticket:'partial-ticket',ids:partial.w.HKCore.eraOrder.map(era=>era+'|'+Object.keys(Object.values(partial.w.dataSets[era].chapters)[0])[0])};return Response.json(partialSession);}if(url.endsWith('/finish')){const answers=JSON.parse(options.body).answers;assert.equal(answers.length,10);assert(!C.answerOK(answers[0].raw,partial.w.HKChallenge.run.qs[0].answers));return Response.json({ms:9000,elapsedMs:9000,correct:9,roundCorrect:9,proof:'partial-proof'});}if(url.endsWith('/register')){partialWrites++;assert.equal(JSON.parse(options.body).proof,'partial-proof');return Response.json({updated:true,entry:{id:'partial',name:'九問正解',ms:9000,correct:9,timestamp:1}});}throw Error('unexpected');};
 partial.click('#startBtn');await new Promise(setImmediate);partial.time(3000);for(let i=0;i<10;i++){partial.time(3000+i*400);partial.answer(i!==0);if(i<9)partial.click('#nextBtn');}await new Promise(setImmediate);await new Promise(setImmediate);
 test('a complete game with an incorrect answer verifies and enables ranking registration',()=>{assert.equal(partial.$('resultCorrect').textContent,'9 / 10');assert.equal(partial.w.HKLeaderboard.registerableBest().correct,9);assert(!partial.$('submit').disabled);assert(partial.$('resultSummary').textContent.includes('5秒'));});
 partial.$('player').value='九問正解';partial.click('#submit');await new Promise(setImmediate);await new Promise(setImmediate);
 test('imperfect results publish the verified best and lead to the personal ranking',()=>{assert.equal(partialWrites,1);assert.equal(partial.navigation,'./ranking.html?registered=1#personalCard');assert.equal(partial.w.HKLeaderboard.readPublished().entry.correct,9);});partial.w.close();
 const cancelled=page();cancelled.w.HKRankingConfig={endpoint:'https://api.example/ranking'};let respond;cancelled.w.fetch=()=>new Promise(resolve=>respond=resolve);cancelled.click('#startBtn');cancelled.click('#quitBtn');respond(Response.json({ticket:'late',ids:Array.from({length:10},(_,i)=>'late'+i)}));await new Promise(setImmediate);
 test('a late start response cannot restart a cancelled challenge',()=>{assert.equal(cancelled.w.HKChallenge.run,null);assert(!cancelled.$('startBox').hidden);});cancelled.dom.window.close();
 console.log(checks+' new challenge checks passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
