const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), { JSDOM } = require('jsdom');
const root = path.resolve(__dirname, '..'), C = require(path.join(root, 'assets/ui/core.js')); let checks = 0;
function test(name, run) { run(); checks++; console.log('PASS', name); }
function page(config = {}) {
  const dom = new JSDOM(fs.readFileSync(path.join(root,'buzzer.html'),'utf8'), { url:'https://historykids.github.io/buzzer.html',runScripts:'outside-only',pretendToBeVisual:true });
  const w=dom.window;let now=0;w.HTMLElement.prototype.scrollIntoView=function(){};Object.defineProperty(w.performance,'now',{value:()=>now});w.setInterval=()=>1;w.clearInterval=()=>{};
  for(const file of ['data/dataset.js','data/ancient.js','assets/ui/core.js','assets/ui/challenge.js'])w.eval(fs.readFileSync(path.join(root,file),'utf8'));
  const $=id=>w.document.getElementById(id),click=s=>{const e=w.document.querySelector(s);assert(e,s);e.click();};
  if(config.game)click(`[data-game="${config.game}"]`);if(config.answers) $('answerMode').value=config.answers;
  if(config.scope) $('mix').value=config.scope;
  const time=t=>{now=t;w.HKChallenge.tick();};
  const start=()=>{click('#startBtn');time(3000);};
  const answer=(correct=true)=>{click('#buzzBtn');const q=w.HKChallenge.run.qs[w.HKChallenge.qi];if(w.HKChallenge.run.answerMode==='choice'){const buttons=[...w.document.querySelectorAll('[data-choice]')];buttons.find(b=>C.answerOK(b.dataset.choice,q.answers)===correct).click();}else{$('answer').value=correct?q.answers.join('・'):'まちがい';$('challengeForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}};
  return {dom,w,$,click,time,start,answer,get now(){return now;}};
}
test('countdown protects answers and elapsed time begins at zero',()=>{const p=page();p.click('#startBtn');p.click('#buzzBtn');assert.equal(p.w.HKChallenge.run.phase,'countdown');p.time(2999);assert.equal(p.$('countdown').textContent,'1');p.time(3000);assert.equal(p.w.HKChallenge.run.phase,'reading');assert.equal(p.$('timerText').textContent,'0.00秒');p.dom.window.close();});
test('questions reveal gradually and freeze when the buzzer is pressed',()=>{const p=page();p.start();p.time(3240);const short=p.$('qTitle').textContent;assert(short.length>0&&short.length<p.w.HKChallenge.run.qs[0].prompt.length);p.click('#buzzBtn');p.time(3500);assert.equal(p.$('qTitle').textContent,short);const options=[...p.w.document.querySelectorAll('[data-choice]')].map(b=>b.dataset.choice);assert.equal(new Set(options.map(s=>[...s].length)).size,1);p.dom.window.close();});
test('wrong answers charge one penalty, break the combo, and save the question for review',()=>{const p=page();p.start();p.answer();p.click('#nextBtn');p.answer(false);assert.equal(p.w.HKChallenge.run.penalty,5000);assert.equal(p.w.HKChallenge.run.combo,0);p.answer(false);assert.equal(p.w.HKChallenge.run.penalty,5000);const q=p.w.HKChallenge.run.log[1].q;assert(JSON.parse(p.w.localStorage.getItem('hk_wrong_v2'))[q.id]);p.dom.window.close();});
test('answer timeout and automatic advance cannot resolve the same round twice',()=>{const p=page();p.start();p.click('#buzzBtn');p.time(18001);assert.equal(p.w.HKChallenge.run.misses,1);p.time(18002);assert.equal(p.w.HKChallenge.run.misses,1);p.time(21000);assert.equal(p.w.HKChallenge.qi,1);assert.equal(p.w.HKChallenge.run.phase,'reading');p.click('#nextBtn');assert.equal(p.w.HKChallenge.qi,1);p.dom.window.close();});
test('60-second rush ends at its limit and does not accept late answers',()=>{const p=page({game:'rush'});p.start();p.answer();p.click('#nextBtn');p.click('#buzzBtn');p.time(63000);assert.equal(p.w.HKChallenge.run.phase,'finished');assert.equal(p.w.HKChallenge.run.correct,1);p.answer();assert.equal(p.w.HKChallenge.run.correct,1);assert(p.$('submitBox').hidden);p.dom.window.close();});
test('three mistakes finish survival and surrender clears the active run',()=>{const p=page({game:'survival'});p.start();for(let i=0;i<3;i++){p.answer(false);if(i<2)p.click('#nextBtn');}assert.equal(p.w.HKChallenge.run.phase,'finished');assert.equal(p.w.HKChallenge.run.lives,0);assert.equal(p.w.HKChallenge.run.log.length,3);assert(p.$('submitBox').hidden);p.click('#settingsBtn');assert.equal(p.w.HKChallenge.run,null);assert(!p.$('startBox').hidden);assert(!p.$('era').disabled);p.dom.window.close();});
test('typing has strict matching and composing Enter cannot submit a mistake',()=>{const p=page({answers:'type'});p.start();p.click('#buzzBtn');p.$('answer').dispatchEvent(new p.w.Event('compositionstart'));p.$('answer').value='まちがい';p.$('challengeForm').dispatchEvent(new p.w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(p.w.HKChallenge.run.misses,0);p.$('answer').dispatchEvent(new p.w.Event('compositionend'));p.$('answer').value=p.w.HKChallenge.run.qs[0].answers.join(' ／ ');p.$('challengeForm').dispatchEvent(new p.w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(p.w.HKChallenge.run.correct,1);p.dom.window.close();});
test('keyboard buzzer and choice work while repeated keys cannot double-answer',()=>{const p=page();p.start();p.w.document.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:' ',code:'Space',bubbles:true,cancelable:true}));assert.equal(p.w.HKChallenge.run.phase,'answer');const q=p.w.HKChallenge.run.qs[0],i=[...p.w.document.querySelectorAll('[data-choice]')].findIndex(b=>C.answerOK(b.dataset.choice,q.answers));p.w.document.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:String(i+1),bubbles:true,cancelable:true}));assert.equal(p.w.HKChallenge.run.correct,1);p.w.document.dispatchEvent(new p.w.KeyboardEvent('keydown',{key:String(i+1),repeat:true,bubbles:true}));assert.equal(p.w.HKChallenge.run.correct,1);p.dom.window.close();});
test('new distractors keep exact lengths and use geography or religion instead of unrelated words',()=>{const p=page();p.start();const q={id:'a',answers:['えど']};const city=C.choiceAnswers(q,[]);assert.deepEqual(new Set(city),new Set(['えど','なら','みと','さが']));const religion=new Set(['じょうど','りんざい','にちれん','そうとう','じしゅう']);for(const correct of religion)for(const choice of C.choiceAnswers({id:correct,answers:[correct]},[]))assert(religion.has(choice));p.dom.window.close();});
(async()=>{
 const p=page({answers:'type'});p.start();for(let i=0;i<10;i++){p.time(3000+i*300);p.answer();if(i<9)p.click('#nextBtn');}
 test('perfect games save combo, review rows and separate ranked answer modes',()=>{assert.equal(p.w.HKChallenge.run.maxCombo,10);assert.equal(p.$('resultReview').querySelectorAll('details').length,10);assert.equal(p.w.HKChallenge.run.group,'v3_allchap_edo_type');assert(!p.$('submitBox').hidden);assert(JSON.parse(p.w.localStorage.getItem(p.w.HKChallenge.run.scoreKey)).correct===10);});
 let written=null,refPath='';p.w.HKCloud={connect:async()=>({auth:{currentUser:{uid:'tester'}},firebase:{firestore:{FieldValue:{serverTimestamp:()=>1}}},db:{doc:route=>{refPath=route;return {get:async()=>({exists:false}),set:async value=>{written=value;}};}}})};p.$('player').value='<script>test</script>';p.click('#submit');await new Promise(setImmediate);await new Promise(setImmediate);
 test('online submission uses a frozen perfect result and a distinct versioned ranking group',()=>{assert(written);assert.equal(written.count,10);assert(refPath.includes('/v3_allchap_edo_type/entries/tester'));assert.equal(written.ms,p.w.HKChallenge.resultMs);assert(p.$('submit').disabled);assert(p.$('note').textContent.includes('送信できた'));});p.dom.window.close();
 console.log(checks+' new challenge checks passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
