const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..');let checks=0;
function test(name,fn){fn();checks++;console.log('PASS',name);}
function page(file,scripts){
 const dom=new JSDOM(fs.readFileSync(path.join(root,file),'utf8'),{url:'https://historykids.github.io/'+file,runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;let now=0,id=0;const timers=new Map();
 w.HTMLElement.prototype.scrollIntoView=function(){};Object.defineProperty(w.performance,'now',{value:()=>now});w.setTimeout=(fn,delay=0)=>{const t=++id;timers.set(t,{fn,due:now+delay});return t;};w.clearTimeout=t=>timers.delete(t);w.setInterval=()=>++id;w.clearInterval=()=>{};w.requestAnimationFrame=()=>++id;w.cancelAnimationFrame=()=>{};w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:()=>()=>{}});
 for(const s of scripts)w.eval(fs.readFileSync(path.join(root,s),'utf8'));
 const $=id=>w.document.getElementById(id),advance=ms=>{const end=now+ms;let count=0;while(true){const next=[...timers.entries()].sort((a,b)=>a[1].due-b[1].due)[0];if(!next||next[1].due>end)break;assert(count++<500,'Timer loop');now=next[1].due;timers.delete(next[0]);next[1].fn();}now=end;};
 return {dom,w,$,advance,timers};
}
test('new pages have unique IDs, existing local assets and valid inline JavaScript',()=>{for(const file of ['figures.html','arcade.html','edogames_poker6.html']){const p=page(file,[]),ids=[...p.w.document.querySelectorAll('[id]')].map(e=>e.id);assert.equal(ids.length,new Set(ids).size,file);for(const e of p.w.document.querySelectorAll('script[src],link[href]')){const url=e.getAttribute('src')||e.getAttribute('href');if(url.startsWith('./'))assert(fs.existsSync(path.join(root,url.split('?')[0])),url);}for(const s of p.w.document.querySelectorAll('script:not([src])'))new (require('node:vm').Script)(s.textContent);p.dom.window.close();}});
test('all six historical guides answer their own suggested questions with reference links',()=>{const p=page('figures.html',['assets/ui/core.js','assets/ui/figures.js']);for(const person of p.w.HKFigures.people){p.w.document.querySelector('[data-person="'+person.id+'"]').click();for(const topic of person.topics){p.w.HKFigures.send(topic);const last=p.$('chatMessages').lastElementChild;assert(last.textContent.length>40);assert(last.querySelector('.sources a'),person.name+topic);}}p.dom.window.close();});
test('history follow-ups preserve context and unsupported modern stories are labelled imaginary',()=>{const p=page('figures.html',['assets/ui/core.js','assets/ui/figures.js']);p.w.HKFigures.send('十七条の憲法って？');p.w.HKFigures.send('もっと詳しく');assert(p.$('chatMessages').lastElementChild.textContent.includes('604年'));p.w.HKFigures.send('スマホは好き？');assert(p.$('chatMessages').lastElementChild.textContent.includes('想像の会話'));p.w.HKFigures.send('ブラックホールの温度は？');assert(p.$('chatMessages').lastElementChild.textContent.includes('まだありません'));p.dom.window.close();});
test('conversation text never executes markup and changing the figure starts a separate history',()=>{const p=page('figures.html',['assets/ui/core.js','assets/ui/figures.js']);p.w.HKFigures.send('<img src=x onerror=alert(1)>');assert.equal(p.$('chatMessages').querySelectorAll('img').length,0);p.w.document.querySelector('[data-person="murasaki"]').click();assert.equal(p.w.HKFigures.history.length,1);assert.equal(p.$('figureName').textContent,'紫式部');p.dom.window.close();});
test('memory boards have exactly two of each visible identity for all sizes and themes',()=>{const p=page('arcade.html',['assets/ui/arcade.js']);for(const theme of ['history','cards'])for(const size of [6,10,15]){p.$('memTheme').value=theme;p.$('memSize').value=size;p.w.HKArcade.startMemory();const counts=new Map();for(const card of p.w.HKArcade.mem.deck)counts.set(card.label,(counts.get(card.label)||0)+1);assert.equal(counts.size,size);assert([...counts.values()].every(x=>x===2));assert.equal(p.$('memoryBoard').children.length,size*2);assert([...p.$('memoryBoard').children].every(b=>b.getAttribute('aria-label').startsWith('裏向き')));}p.dom.window.close();});
test('memory rejects duplicate and third flips, resolves each pair once, and records completion',()=>{const p=page('arcade.html',['assets/ui/arcade.js']);p.$('memSize').value='6';p.w.HKArcade.startMemory();const m=p.w.HKArcade.mem;for(let key=0;key<6;key++){const pair=m.deck.map((c,i)=>c.key===key?i:-1).filter(i=>i>=0);assert(p.w.HKArcade.flipMemory(pair[0]));assert.equal(p.w.HKArcade.flipMemory(pair[0]),false);assert(p.w.HKArcade.flipMemory(pair[1]));assert.equal(p.w.HKArcade.flipMemory((pair[1]+1)%12),false);p.advance(600);}assert(m.finished);assert.equal(m.score[0],6);assert.equal(m.moves,6);assert(!p.$('memResult').hidden);assert(JSON.parse(p.w.localStorage.getItem(m.key)));p.dom.window.close();});
test('memory mismatch changes player, hint is one-time, and a restart cancels stale callbacks',()=>{const p=page('arcade.html',['assets/ui/arcade.js']);p.$('memMode').value='duo';p.w.HKArcade.startMemory();let m=p.w.HKArcade.mem;const b=m.deck.findIndex(c=>c.key!==m.deck[0].key);p.w.HKArcade.flipMemory(0);p.w.HKArcade.flipMemory(b);p.advance(1000);assert.equal(m.turn,1);assert.equal(m.open.length,0);p.$('memPeek').click();assert.equal(m.penalty,5);p.$('memPeek').click();assert.equal(m.penalty,5);p.w.HKArcade.startMemory();m=p.w.HKArcade.mem;p.advance(3000);assert.equal(m.moves,0);assert(!m.lock);assert(!m.peeking);p.dom.window.close();});
test('CPU memory starts with no hidden knowledge and continues a legal two-card turn',()=>{const p=page('arcade.html',['assets/ui/arcade.js']);p.$('memMode').value='cpu';p.w.HKArcade.startMemory();const m=p.w.HKArcade.mem;assert.equal(m.known.size,0);const b=m.deck.findIndex(c=>c.key!==m.deck[0].key);p.w.HKArcade.flipMemory(0);p.w.HKArcade.flipMemory(b);p.advance(1000);assert.equal(m.turn,1);assert.equal(p.w.HKArcade.flipMemory(0),false);p.advance(1400);assert(m.moves>=2);assert(m.open.length<=2);p.dom.window.close();});
test('changing games pauses memory time and CPU callbacks until returning',()=>{const p=page('arcade.html',['assets/ui/arcade.js']);p.w.HKArcade.startMemory();p.w.document.querySelector('[data-arcade="war"]').click();const m=p.w.HKArcade.mem;assert(m.paused);p.advance(10000);p.w.document.querySelector('[data-arcade="memory"]').click();assert(!m.paused);assert.equal(m.started,10000);p.dom.window.close();});
test('GRID WAR builds passable maps and enemies find a step around walls',()=>{const p=page('arcade.html',['assets/ui/arcade.js']);for(const name of ['town','gate','garden']){p.$('warMap').value=name;p.w.HKArcade.startWar();const w=p.w.HKArcade.war;assert.equal(w.player.hp,100);assert(w.walls.size>5);assert.equal(w.enemies.length,3);const step=p.w.HKArcade.pathStep({x:72,y:168},{x:876,y:168});assert(!w.walls.has(Math.floor(step.x/48)+','+Math.floor(step.y/48)));assert.equal(p.w.HKArcade.lineClear({x:72,y:168},{x:876,y:168}),false);}p.dom.window.close();});
test('GRID WAR bullets stop at walls and never damage an opponent through cover',()=>{const p=page('arcade.html',['assets/ui/arcade.js']);p.w.HKArcade.startWar();const w=p.w.HKArcade.war;w.player.x=200;w.player.y=168;w.enemies=[{x:300,y:168,hp:65,maxHp:65,speed:0,shoot:999,nav:999,target:{x:300,y:168}}];p.w.HKArcade.shoot();for(let i=0;i<12;i++)p.w.HKArcade.tickWar(.05);assert.equal(w.enemies[0].hp,65);assert.equal(w.bullets.length,0);p.dom.window.close();});
test('GRID WAR reload, dash cooldown, pause and mission completion have consistent state',()=>{const p=page('arcade.html',['assets/ui/arcade.js']);p.w.HKArcade.startWar();const w=p.w.HKArcade.war;w.ammo=0;p.w.HKArcade.reload();assert(w.reload>0);for(let i=0;i<32;i++)p.w.HKArcade.tickWar(.05);assert.equal(w.ammo,24);p.w.HKArcade.dash();assert.equal(w.dashWait,4);p.w.HKArcade.tickWar(.05);p.w.HKArcade.dash();assert(w.dashWait<4);p.$('warPause').click();const t=w.time;p.w.HKArcade.tickWar(.05);assert.equal(w.time,t);p.$('warPause').click();w.time=89.98;p.w.HKArcade.tickWar(.05);assert(w.finished);assert(!p.$('warResult').hidden);assert(p.$('warOverlay').textContent.includes('CLEAR'));p.dom.window.close();});
test('capture mode requires the objective, awards progress points and stops at 100 percent',()=>{const p=page('arcade.html',['assets/ui/arcade.js']);p.$('warMode').value='capture';p.w.HKArcade.startWar();const w=p.w.HKArcade.war;w.enemies=[];w.player.x=480;w.player.y=288;w.capture=99.8;w.captureScore=199;p.w.HKArcade.tickWar(.05);assert(w.finished);assert.equal(w.capture,100);assert(w.score>0);p.dom.window.close();});
function poker(){const p=page('edogames_poker6.html',[]);for(const s of p.w.document.querySelectorAll('script:not([src])'))if(s.textContent.trim())p.w.eval(s.textContent);p.w.eval(fs.readFileSync(path.join(root,'assets/ui/poker-practice.js'),'utf8'));return p;}
test('CPU poker starts and plays full hands without Firebase or leaking opponent cards',()=>{const p=poker();assert(!p.w.firebase);p.w.HKPokerPractice.startPractice();assert(p.w.HKPokerPractice.local);assert.equal(Object.keys(p.w.roomData.players).length,4);assert(p.$('s-game').classList.contains('on'));assert.equal(p.$('opponents-grid').querySelectorAll('[data-card]').length,0);let rounds=0;while(p.w.roomData.status==='playing'&&rounds++<100){const actor=p.w.playerBySeat(p.w.roomData,p.w.roomData.turnSeat);if(actor.id===p.w.myId)p.w.playerAction(p.w.roomData.currentBet>actor.p.currentBet?'call':'check');else p.advance(800);}assert(rounds<100);assert(['showdown','gameover'].includes(p.w.roomData.status));const total=Object.values(p.w.roomData.players).reduce((n,x)=>n+x.chips,0);assert.equal(total,4000);assert(!p.$('showdown-box').hidden);p.dom.window.close();});
test('poker evaluator handles wheel straights, kickers and multiple side pots',()=>{const p=poker();assert.equal(p.w.evaluateFive(['AS','2H','3D','4C','5S']).score[1],5);assert(p.w.compareScore(p.w.evaluateFive(['AS','AH','KD','QC','JS']).score,p.w.evaluateFive(['AS','AH','QD','JC','TS']).score)>0);const pots=p.w.buildSidePots([{id:'a',invested:50,folded:false},{id:'b',invested:100,folded:false},{id:'c',invested:100,folded:false}]);assert.equal(pots.reduce((n,x)=>n+x.amount,0),250);assert.equal(pots.length,2);p.dom.window.close();});
test('poker CPU decisions cannot depend on opponents holes or future deck cards',()=>{const p=poker();p.w.HKPokerPractice.startPractice();const a=JSON.parse(JSON.stringify(p.w.roomData));const id='cpu0';const d1=p.w.HKPokerPractice.chooseBot(a,id,()=>.4);for(const [pid,player]of Object.entries(a.players))if(pid!==id)player.hole='["AS","AH"]';a.deck='["AS","AH"]';const d2=p.w.HKPokerPractice.chooseBot(a,id,()=>.4);assert.equal(JSON.stringify(d1),JSON.stringify(d2));p.dom.window.close();});
test('poker bet presets respect min/max and winning five cards are highlighted',()=>{const p=poker();p.w.HKPokerPractice.startPractice();p.w.roomData.currentBet=100;p.w.roomData.minRaise=100;p.w.document.querySelector('[data-preset="0"]').click();assert.equal(Number(p.$('bet-amount').value),200);const me=p.w.roomData.players[p.w.myId];me.hole='["AS","KH"]';p.w.roomData.community='["QD","JC","TS"]';p.w.renderGame(p.w.roomData);assert.equal(p.w.document.querySelectorAll('#my-cards .best-five,#community .best-five').length,5);p.w.cleanupLocal();p.advance(5000);assert(!p.w.HKPokerPractice.local);p.dom.window.close();});
test('a knocked-out poker player can watch a later flop without a missing-hand error',()=>{const p=poker();p.w.HKPokerPractice.startPractice();const me=p.w.roomData.players[p.w.myId];me.out=true;me.hole='[]';p.w.roomData.community='["QD","JC","TS"]';p.w.renderGame(p.w.roomData);assert.equal(p.$('current-hand-name').textContent,'今回は観戦中');p.dom.window.close();});
test('online memory serializes concurrent flips and resolves a pending pair only once',()=>{
 const p=page('edogames.html',[]);let room={status:'playing',cards:'["♠A","♠A","♥2","♥2"]',matched:'[]',pending:'[]',flipped:'[]',turn:'host',host:{score:0},guest:{score:0}};let listener,transactions=0;
 const ref={on(type,cb){if(type==='value'){listener=cb;cb({val:()=>room});}return cb;},off(){},transaction(fn){transactions++;const next=fn(JSON.parse(JSON.stringify(room)));if(next){room=next;listener?.({val:()=>room});}return Promise.resolve();}};
 p.w.firebase={initializeApp:()=>({}),database:()=>({ref:()=>({on(){}})})};
 for(const s of p.w.document.querySelectorAll('script:not([src])'))if(s.textContent.trim())p.w.eval(s.textContent);
 p.w.roomRef=ref;p.w.myRole='host';p.w.myName='A';p.w.enName='B';p.w.currentGame='memory';p.w.gameActive=true;p.w.startMemory();p.w.onMemCardClick(0);p.w.onMemCardClick(1);listener({val:()=>room});listener({val:()=>room});p.advance(1100);assert.equal(room.host.score,1);assert.equal(JSON.parse(room.matched).length,2);assert(p.w.memCanClick);assert(p.$('mem-board').children[2].disabled===false);p.advance(3000);assert.equal(room.host.score,1);p.w.onMemCardClick(2);p.w.onMemCardClick(3);p.advance(1100);assert.equal(room.winner,'host');assert.equal(p.$('result-title').textContent,'VICTORY');assert.equal(p.w.memMyScore,2);p.dom.window.close();
});
(async()=>{
 const p=page('figures.html',['assets/ui/core.js','assets/ui/figures.js']);let instance;Object.defineProperty(p.w.navigator,'gpu',{value:{requestAdapter:async()=>({features:new Set(['shader-f16'])})}});p.w.Worker=class{constructor(){instance=this;}postMessage(x){this.last=x;}terminate(){this.dead=true;}};
 p.$('enableAI').click();await new Promise(setImmediate);instance.onmessage({data:{type:'ready'}});p.w.HKFigures.send('十七条の憲法って？');
 test('local AI sends the selected persona, references and bounded chat history to the worker',()=>{assert.equal(instance.last.type,'chat');assert(instance.last.messages[0].content.includes('聖徳太子'));assert(instance.last.messages[0].content.includes('604年'));assert(instance.last.messages.length<=7);assert(p.$('chatInput').disabled);});
 const id=instance.last.id;instance.onmessage({data:{type:'token',id,text:'協力することが大切です。'}});instance.onmessage({data:{type:'done',id,text:'協力することが大切です。'}});
 test('AI streams plain text, waits for interrupted generation and falls back on a failed request',()=>{assert(!p.$('chatInput').disabled);assert(p.$('chatMessages').lastElementChild.textContent.includes('協力'));assert(p.$('chatMessages').lastElementChild.querySelector('a'));p.w.HKFigures.send('こんにちは');const stopId=instance.last.id;p.$('stopChat').click();assert.equal(instance.last.type,'stop');assert(p.$('chatInput').disabled);instance.onmessage({data:{type:'done',id:stopId,text:'こんにちは'}});assert(!p.$('chatInput').disabled);p.w.HKFigures.send('こんにちは');instance.onmessage({data:{type:'error',id:instance.last.id,text:'device lost'}});assert(instance.dead);assert(!p.$('chatInput').disabled);assert(p.$('engineBadge').textContent.includes('資料会話'));});p.dom.window.close();
 const cpu=page('figures.html',['assets/ui/core.js','assets/ui/figures.js']);let cpuWorker;cpu.w.Worker=class{constructor(){cpuWorker=this;}postMessage(x){this.last=x;}terminate(){}};cpu.$('enableAI').click();await new Promise(setImmediate);
 test('devices without a GPU select real WebAssembly inference rather than rejecting AI',()=>{assert.equal(cpuWorker.last.type,'load');assert.equal(cpuWorker.last.device,'cpu');assert(cpu.$('engineProgress').hidden===false);cpuWorker.onmessage({data:{type:'ready',device:'cpu'}});assert(cpu.$('engineBadge').textContent.includes('生成AI'));});cpu.dom.window.close();
 const q=page('figures.html',['assets/ui/core.js','assets/ui/figures.js']);q.$('enableAI').click();await new Promise(setImmediate);
 test('unsupported devices keep usable guide mode without claiming the AI started',()=>{assert(q.$('engineStatus').textContent.includes('使えません'));assert(q.$('engineBadge').textContent.includes('資料会話'));q.w.HKFigures.send('十七条の憲法');assert(q.$('chatMessages').lastElementChild.textContent.includes('604年'));});q.dom.window.close();
 console.log(checks+' game and conversation checks passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
