const assert=require('node:assert/strict'),{DatabaseSync}=require('node:sqlite');
(async()=>{
 const {default:worker,HistoryLeaderboard}=await import('../server/figure-api/worker.mjs'),{questions}=await import('../server/figure-api/ranking-questions.mjs');
 const db=new DatabaseSync(':memory:'),ctx={storage:{sql:{exec(query,...args){if(!args.length&&query.includes(';')){db.exec(query);return{toArray:()=>[]};}const stmt=db.prepare(query);return{toArray:()=>stmt.all(...args)};}}}};
 // Cloudflare exec executes mutations immediately, so wrap the cursor after running each statement.
 ctx.storage.sql.exec=(query,...args)=>{if(!args.length&&query.includes(';')){db.exec(query);return{toArray:()=>[]};}const stmt=db.prepare(query);if(/^SELECT/i.test(query))return{toArray:()=>stmt.all(...args)};stmt.run(...args);return{toArray:()=>[]};};
 let board=new HistoryLeaderboard(ctx),limited=false,now=Date.now();const originalNow=Date.now;Date.now=()=>now;
 const limiter={limit:async()=>({success:!limited})},env={LEADERBOARD:{idFromName:n=>n,get:()=>({fetch:req=>board.fetch(req)})},RANK_READ_LIMITER:limiter,RANK_WRITE_LIMITER:limiter,RANK_GLOBAL_LIMITER:limiter};let checks=0;
 async function request(path,body,token='a'.repeat(64),origin='https://historykids.github.io'){const r=await worker.fetch(new Request('https://api.example'+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})}),env);return{status:r.status,body:await r.json()};}
 async function test(name,fn){await fn();checks++;console.log('PASS',name);}
 let session,receipt;
 await test('public board is empty and private bearer credentials are never public IDs',async()=>{const r=await request('/ranking');assert.equal(r.status,200);assert.deepEqual(r.body.entries,[]);assert.notEqual(r.body.uid,'a'.repeat(64));});
 await test('server chooses exactly one question from each of ten eras',async()=>{session=(await request('/ranking/start',{})).body;assert.equal(session.ids.length,10);assert.equal(new Set(session.ids.map(id=>questions.find(q=>q.id===id).era)).size,10);assert(session.ticket);});
 const log=()=>session.ids.map(id=>({id,raw:questions.find(q=>q.id===id).answers.join('・')}));
 await test('wrong, missing and reordered answers cannot create a verified record',async()=>{now+=10000;for(const answers of [[],log().slice(0,9),log().reverse(),log().map((a,i)=>i? a:{...a,raw:'偽の答え'})])assert.equal((await request('/ranking/finish',{ticket:session.ticket,answers})).status,400);assert.equal((await request('/ranking/register',{name:'偽',proof:'none',ms:1})).status,409);});
 await test('all ten answers are checked and the server clock ignores a forged client time',async()=>{now+=5000;const r=await request('/ranking/finish',{ticket:session.ticket,answers:log(),ms:1});assert.equal(r.status,200);receipt=r.body;assert.equal(receipt.ms,12000);assert(receipt.proof);assert.equal((await request('/ranking/finish',{ticket:session.ticket,answers:log()})).status,409);});
 await test('a verified nickname can be published once and read after a Durable Object restart',async()=>{const r=await request('/ranking/register',{name:'歴史名人',proof:receipt.proof});assert.equal(r.status,200);assert(r.body.updated);board=new HistoryLeaderboard(ctx);const read=(await request('/ranking')).body;assert.equal(read.entries[0].name,'歴史名人');assert.equal(read.own.ms,12000);assert.equal((await request('/ranking/register',{name:'遅い名前',proof:receipt.proof})).body.updated,false);});
 await test('another browser cannot read, change or claim the first browser record',async()=>{const r=(await request('/ranking',undefined,'b'.repeat(64))).body;assert.equal(r.own,null);assert.equal(r.entries.length,1);assert.equal((await request('/ranking/register',{name:'横取り',proof:receipt.proof},'b'.repeat(64))).status,409);});
 await test('a slower challenge preserves the fastest receipt and name',async()=>{session=(await request('/ranking/start',{})).body;now+=25000;const slow=(await request('/ranking/finish',{ticket:session.ticket,answers:log()})).body;assert.equal(slow.ms,receipt.ms);assert.equal(slow.proof,receipt.proof);assert.equal((await request('/ranking/register',{name:'遅い',proof:slow.proof})).body.entry.name,'歴史名人');});
 await test('a faster challenge atomically replaces the personal best and uses safe nickname text',async()=>{session=(await request('/ranking/start',{})).body;now+=8000;const fast=(await request('/ranking/finish',{ticket:session.ticket,answers:log()})).body;assert.equal(fast.ms,5000);const r=await request('/ranking/register',{name:"<img onerror=1>';DROP TABLE scores;",proof:fast.proof});assert(r.body.updated);assert.equal(Array.from(r.body.entry.name).length,24);assert.equal((await request('/ranking')).body.entries.length,1);});
 await test('expired challenges and unrealistically early finishes are rejected',async()=>{session=(await request('/ranking/start',{})).body;assert.equal((await request('/ranking/finish',{ticket:session.ticket,answers:log()})).status,400);now+=31*60000;assert.equal((await request('/ranking/finish',{ticket:session.ticket,answers:log()})).status,409);});
 await test('origin, method, credentials and rate limits guard the public API',async()=>{assert.equal((await request('/ranking',undefined,'','https://evil.example')).status,403);assert.equal((await request('/ranking/start',undefined)).status,405);assert.equal((await request('/ranking/start',{},'')).status,401);assert.equal((await request('/ranking/start',{},'bad')).status,401);limited=true;assert.equal((await request('/ranking')).status,429);});
 Date.now=originalNow;db.close();console.log(checks+' server ranking checks passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
