const assert=require('node:assert/strict'),{DatabaseSync}=require('node:sqlite');
(async()=>{
 const {default:worker,HistoryLeaderboard}=await import('../server/ranking-api/worker.mjs'),{questions}=await import('../server/figure-api/ranking-questions.mjs');
 const db=new DatabaseSync(':memory:'),ctx={storage:{sql:{exec(query,...args){if(!args.length&&query.includes(';')){db.exec(query);return{toArray:()=>[]};}const stmt=db.prepare(query);return{toArray:()=>stmt.all(...args)};}}}};
 // Cloudflare exec executes mutations immediately, so wrap the cursor after running each statement.
 ctx.storage.sql.exec=(query,...args)=>{if(!args.length&&query.includes(';')){db.exec(query);return{toArray:()=>[]};}const stmt=db.prepare(query);if(/^(SELECT|PRAGMA)/i.test(query))return{toArray:()=>stmt.all(...args)};stmt.run(...args);return{toArray:()=>[]};};
 let board=new HistoryLeaderboard(ctx),limited=false,now=Date.now();const originalNow=Date.now;Date.now=()=>now;
 const limiter={limit:async()=>({success:!limited})},env={LEADERBOARD:{idFromName:n=>n,get:()=>({fetch:req=>board.fetch(req)})},RANK_READ_LIMITER:limiter,RANK_WRITE_LIMITER:limiter,RANK_GLOBAL_LIMITER:limiter};let checks=0;
 async function request(path,body,token='a'.repeat(64),origin='https://historykids.github.io'){const r=await worker.fetch(new Request('https://api.example'+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})}),env);return{status:r.status,body:await r.json()};}
 async function test(name,fn){await fn();checks++;console.log('PASS',name);}
 let session,receipt;
 await test('public board is empty and private bearer credentials are never public IDs',async()=>{const r=await request('/ranking');assert.equal(r.status,200);assert.deepEqual(r.body.entries,[]);assert.notEqual(r.body.uid,'a'.repeat(64));});
 await test('server chooses exactly one question from each of ten eras',async()=>{session=(await request('/ranking/start',{})).body;assert.equal(session.ids.length,10);assert.equal(new Set(session.ids.map(id=>questions.find(q=>q.id===id).era)).size,10);assert(session.ticket);});
 const log=()=>session.ids.map(id=>({id,raw:questions.find(q=>q.id===id).answers.join('・')}));
 await test('missing, malformed and reordered answers cannot create a verified record',async()=>{now+=10000;for(const answers of [[],log().slice(0,9),log().reverse(),log().map((a,i)=>i? a:{...a,raw:null})])assert.equal((await request('/ranking/finish',{ticket:session.ticket,answers})).status,400);assert.equal((await request('/ranking/register',{name:'偽',proof:'none',ms:1})).status,409);});
 await test('all ten answers are checked, forged client time is ignored and retry preserves the time',async()=>{now+=5000;const r=await request('/ranking/finish',{ticket:session.ticket,answers:log(),ms:1});assert.equal(r.status,200);receipt=r.body;assert.equal(receipt.ms,12000);assert(receipt.proof);now+=1000;assert.deepEqual((await request('/ranking/finish',{ticket:session.ticket,answers:log()})).body,receipt);});
 await test('a verified nickname can be published once and read after a Durable Object restart',async()=>{const r=await request('/ranking/register',{name:'歴史名人',proof:receipt.proof});assert.equal(r.status,200);assert(r.body.updated);board=new HistoryLeaderboard(ctx);const read=(await request('/ranking')).body;assert.equal(read.entries[0].name,'歴史名人');assert.equal(read.own.ms,12000);assert.equal((await request('/ranking/register',{name:'歴史名人',proof:receipt.proof})).body.updated,false);});
 await test('another browser cannot read, change or claim the first browser record',async()=>{const r=(await request('/ranking',undefined,'b'.repeat(64))).body;assert.equal(r.own,null);assert.equal(r.entries.length,1);assert.equal((await request('/ranking/register',{name:'横取り',proof:receipt.proof},'b'.repeat(64))).status,409);});
 await test('a slower challenge keeps the best time and timestamp while updating the selected nickname',async()=>{session=(await request('/ranking/start',{})).body;now+=25000;const slow=(await request('/ranking/finish',{ticket:session.ticket,answers:log()})).body;assert.equal(slow.ms,receipt.ms);assert.equal(slow.proof,receipt.proof);const before=(await request('/ranking')).body.own;const renamed=(await request('/ranking/register',{name:'選んだ名前',proof:slow.proof})).body;assert(renamed.updated);assert(renamed.renamed);assert.equal(renamed.entry.name,'選んだ名前');assert.equal(renamed.entry.ms,before.ms);assert.equal(renamed.entry.timestamp,before.timestamp);assert.equal((await request('/ranking')).body.entries[0].name,'選んだ名前');});
 await test('a faster challenge atomically replaces the personal best and uses safe nickname text',async()=>{session=(await request('/ranking/start',{})).body;now+=8000;const fast=(await request('/ranking/finish',{ticket:session.ticket,answers:log()})).body;assert.equal(fast.ms,5000);const r=await request('/ranking/register',{name:"<img onerror=1>';DROP TABLE scores;",proof:fast.proof});assert(r.body.updated);assert.equal(Array.from(r.body.entry.name).length,24);assert.equal((await request('/ranking')).body.entries.length,1);});
 await test('previously published records and ownership survive adding correctness to legacy tables',async()=>{const before=(await request('/ranking')).body.own;db.exec('ALTER TABLE scores DROP COLUMN correct; ALTER TABLE receipts DROP COLUMN correct;');board=new HistoryLeaderboard(ctx);assert.deepEqual((await request('/ranking')).body.own,before);assert.equal((await request('/ranking/register',{name:before.name,proof:db.prepare('SELECT proof FROM receipts').get().proof})).status,200);});
 await test('nine correct answers can publish with a server-calculated five-second penalty',async()=>{const token='d'.repeat(64),game=(await request('/ranking/start',{},token)).body;now+=8000;const answers=game.ids.map((id,i)=>({id,raw:i?questions.find(q=>q.id===id).answers.join('・'):'間違い'}));const finished=(await request('/ranking/finish',{ticket:game.ticket,answers,ms:1,correct:10,penaltyMs:0},token)).body;assert.equal(finished.correct,9);assert.equal(finished.roundCorrect,9);assert.equal(finished.durationMs,5000);assert.equal(finished.penaltyMs,5000);assert.equal(finished.ms,10000);const published=(await request('/ranking/register',{name:'九問正解',proof:finished.proof},token)).body;assert.equal(published.entry.correct,9);assert.equal(published.entry.ms,10000);const read=(await request('/ranking',undefined,token)).body;assert.equal(read.own.correct,9);assert(read.entries.some(r=>r.name==='九問正解'&&r.correct===9));now+=2000;assert.deepEqual((await request('/ranking/finish',{ticket:game.ticket,answers},token)).body,finished);});
 await test('zero correct answers and timeouts remain eligible after completing all ten questions',async()=>{const token='e'.repeat(64),game=(await request('/ranking/start',{},token)).body;now+=8000;const answers=game.ids.map(id=>({id,raw:'読み時間切れ'}));const finished=(await request('/ranking/finish',{ticket:game.ticket,answers},token)).body;assert.equal(finished.correct,0);assert.equal(finished.penaltyMs,50000);assert.equal(finished.ms,55000);assert.equal((await request('/ranking/register',{name:'最後まで挑戦',proof:finished.proof},token)).status,200);});
 await test('expired challenges and unrealistically early finishes are rejected',async()=>{session=(await request('/ranking/start',{})).body;assert.equal((await request('/ranking/finish',{ticket:session.ticket,answers:log()})).status,400);now+=31*60000;assert.equal((await request('/ranking/finish',{ticket:session.ticket,answers:log()})).status,409);});
 await test('origin, method, credentials and rate limits guard the public API',async()=>{assert.equal((await request('/ranking',undefined,'','https://evil.example')).status,403);assert.equal((await request('/ranking/start',undefined)).status,405);assert.equal((await request('/ranking/start',{},'')).status,401);assert.equal((await request('/ranking/start',{},'bad')).status,401);limited=true;assert.equal((await request('/ranking')).status,429);});
 Date.now=originalNow;db.close();console.log(checks+' server ranking checks passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
